Update manuallint.yml

diff --git a/.github/workflows/manuallint.yml b/.github/workflows/manuallint.yml
--- a/.github/workflows/manuallint.yml
+++ b/.github/workflows/manuallint.yml
@@ -14,14 +14,24 @@ jobs:
     - name: Install libraries
       run: |
         python -m pip install autoflake isort black
+         
+    ##Autoflake does not return code 1 when changes are needed so we capture the output to manually return code 1 if needed.
     - name: Run autoflake 
       if: always()
       run: | 
-       autoflake . -r --remove-all-unused-imports
+       output="$(autoflake . -r --remove-all-unused-imports)"
+       if [[ -n $output ]]
+       then
+        exit 1
+       else
+        exit 0
+       fi
+             
     - name: Run isort 
       if: always()
       run: |
         isort . --diff -c
+        
     - name: Run black 
       if: always()
       run: |
